version: '3.7'

services:
  ssh:
    build:
      context: ssh
      target: development
    volumes:
      - ./ssh:/go/src/github.com/gustavosbarreto/devicehub/ssh
      - secrets:/var/run/secrets
  api:
    build:
      context: api
      target: development
    volumes:
      - ./api:/go/src/github.com/gustavosbarreto/devicehub/api
      - secrets:/var/run/secrets
  ws:
    build:
      context: ws
      target: development
    volumes:
      - ./ws:/go/src/github.com/gustavosbarreto/devicehub/ws
  ui:
    build:
      context: ui
      target: development
    volumes:
      - ./ui:/src
  gateway:
    build:
      context: gateway
  agent:
    build:
      context: agent
      target: development
    environment:
      - SERVER_ADDRESS=http://172.17.0.1:80
      - PRIVATE_KEY=/var/run/secrets/devicehub.key
    volumes:
      - ./agent:/go/src/github.com/gustavosbarreto/devicehub/agent
      - secrets:/var/run/secrets
    depends_on:
      - emq
      - api
      - ssh
      - gateway

secrets:
  ssh_private_key:
    external: true
  api_private_key:
    external: true
  api_public_key:
    external: true

volumes:
  secrets:
