version: 2.1

executors:
  docker:
    environment:
      API_IMAGE_NAME: shellhubio/shellhub-api
      SSH_IMAGE_NAME: shellhubio/shellhub-ssh
      UI_IMAGE_NAME: shellhubio/shellhub-ui
      GATEWAY_IMAGE_NAME: shellhubio/shellhub-gateway
      AGENT_IMAGE_NAME: shellhubio/agent
      DOCKER_CLI_EXPERIMENTAL: enabled
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build API microservice
          working_directory: api
          command: docker build -t $API_IMAGE_NAME:$CIRCLE_SHA1 .
      - run:
          name: Build SSH microservice
          working_directory: ssh
          command: docker build -t $SSH_IMAGE_NAME:$CIRCLE_SHA1 .
      - run:
          name: Build UI microservice
          working_directory: ui
          command: docker build -t $UI_IMAGE_NAME:$CIRCLE_SHA1 .
      - run:
          name: Build API Gateway microservice
          working_directory: gateway
          command: docker build -t $GATEWAY_IMAGE_NAME:$CIRCLE_SHA1 .
      - run:
          name: Build agent images
          working_directory: agent
          command: |
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker build -f Dockerfile.amd64 -t $AGENT_IMAGE_NAME:${CIRCLE_SHA1}-amd64 .
            docker build -f Dockerfile.arm32v6 -t $AGENT_IMAGE_NAME:${CIRCLE_SHA1}-arm32v6 .
            docker build -f Dockerfile.arm64v8 -t $AGENT_IMAGE_NAME:${CIRCLE_SHA1}-arm64v8 .
          no_output_timeout: 20m
      - run:
          name: Archive Docker images
          command: |
            docker save $(docker images | awk '{if ($1 ~ /shellhubio\//) print $3}') -o images.tar
            docker images | awk '{if ($1 ~ /shellhubio\//) print $1 " " $2 " " $3}' > tags.txt
      - persist_to_workspace:
          root: .
          paths:
            - ./images.tar
            - ./tags.txt
  push:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Setup DockerHub credentials
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Load archived Docker images
          command: |
            docker load -i /tmp/workspace/images.tar
            awk '{ print "docker tag "$3" "$1":"$2"" | "/bin/sh"}' /tmp/workspace/tags.txt
      - run:
          name: Publish API microservice image
          command: ./.circleci/push.sh $API_IMAGE_NAME
      - run:
          name: Publish SSH microservice image
          command: ./.circleci/push.sh $SSH_IMAGE_NAME
      - run:
          name: Publish UI microservice image
          command: ./.circleci/push.sh $UI_IMAGE_NAME
      - run:
          name: Publish API Gateway microservice image
          command: ./.circleci/push.sh $GATEWAY_IMAGE_NAME
      - run:
          name: Publish agent images
          command: ./.circleci/push-multiarch.sh $AGENT_IMAGE_NAME
workflows:
  version: 2
  master:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - /feature\/.*/
            tags:
              only: /.*/
      - push:
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              only: /.*/
