blank_issues_enabled: false
contact_links:
  - name: Feature Request
    about: Suggest a new feature or improvement
    url: https://github.com/shellhub-io/shellhub/discussions/categories/ideas
  - name: Question
    about: Get help from the community
    url: https://github.com/shellhub-io/shellhub/discussions/categories/q-a
