root = "../../"
tmp_dir = "/tmp/air"

[build]
pre_cmd = []
cmd = "go build -tags enterprise -o /tmp/air/main github.com/shellhub-io/shellhub/api"
post_cmd = []
bin = "/tmp/air/main"
full_bin = ""
args_bin = [
    "server",
]
delay = 500
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
include_dir = ["shellhub/api", "shellhub/openapi", "cloud"]
include_ext = ["go", "tpl", "tmpl", "html", "yaml", "yml", "json"]
include_file = []
kill_delay = "0s"
log = "build-errors.log"
poll = false
poll_interval = 0
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = false
